# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: cachix

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: 'Ref/branch to check'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enable Cachix
        uses: cachix/cachix-action@v15
        with:
          name: doom-emacs-unstraightened
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          cachixArgs: '-v'
      - name: Cache downloads
        uses: ./.github/actions/cache-downloads
      - name: Build packages for Cachix
        run: nix build .#cachix-packages
